#!/bin/sh

# Run lint on all packages
echo "Running linter..."
pnpm -r --filter './packages/**' run lint || exit 1

# Run format check
echo "Checking code formatting..."
pnpm -r --filter './packages/**' run format || exit 1

# Run tests
echo "Running tests..."
pnpm -r --filter './packages/**' run test || exit 1
